### ISSUE TITLE
Էս պրոյեկտները դու ես մտածում թե քեզ տնային են տալիս?

### ISSUE THREAD

**Issue by hisusqristos** [aniordyan/carRentingSystem#1]
Որովհետև բարդ բաներ ես վերցնում, չես կարծում?

կստածի փլեյլիստի պրոյեկտը ինչ եղավ? շատ հետաքրքիր ա

ոտքս խերով լինի ձեր իշյուներ, այս երգը ձեզ.

https://youtu.be/nMuTgStG8w0?si=8a6RVv0jCTsCMM22

**Comment by aniordyan** [comment]
չէէ էս տիպի մտքերը մենակ իմ գլխին ա փչում ((
էս քառը more simple backup plan էր
իհարկե կարծում եմ, եվ զգացել եմ դա)) at least it was fun, it wasnt ideal, but it was fun (մխիթարում եմ ինձ ահահ)
8/10 փակեցի փլեյրը
մի քանի հատ բարդություն կար, բայց վ ցելոմ աշխատում ա
զատո մենակ փլեյրի վրա աշխատելով ահագին բան սովորեցի

հգ երգը լավն էր))) ու վաս օչեն տոնկի վկուս
![audioplayer](https://github.com/aniordyan/carRentingSystem/assets/77895035/d9fd55da-8de9-4729-9b4b-d285aea7ee20)

**Comment by aniordyan** [comment]
նոր եմ տենում
փլեյրի սխալ ռեփոն ես լայքել ահահ

**Comment by hisusqristos** [comment]
> չէէ էս տիպի մտքերը մենակ իմ գլխին ա փչում ((

նախ կոմպլիմենտ անեմ ձեր ձգտումը պրակտիկ բաներ սարքելու, սյո ժե եթե սովորական բաներից հոգնես ու քեզ ինչ-որ «խենթություններ» պետք գան առխեին գրի խորհրդակցվենք։

հաճելի զայցեվ-նետ վայբեր ունի սարքածդ։ Քո լիքը նոր բաներ սովորելը շարունակական բնույթ ա կրելու դառնաս ակուլա

**Comment by aniordyan** [comment]
> նախ կոմպլիմենտ անեմ ձեր ձգտումը պրակտիկ բաներ սարքելու, սյո ժե եթե սովորական բաներից հոգնես ու քեզ ինչ-որ «խենթություններ» պետք գան առխեին գրի խորհրդակցվենք։

աաաաա անպայման, քու հետ մեծ հաճույքով կաշխատեմ <3
ես ավելի շատ իրան windows 7 media player-ի հետ էի նմանացնում ><

**Comment by hisusqristos** [comment]
Շատ լավա, մենք ձեզ հասկացանք

դե կարաս արդեն փակես իշյուն, հարցը լուժեցինք :Դ
